# https://www.hanover.edu/academics/programs?gclid=CKip3r6Z7M8CFQsfhgodfbAHKQ

degrees = [
    'Other',
    'Anthropology',
    'Art (Studio Art)',
    'Art History',
    'Astronomy',
    'Biochemistry',
    'Biology',
    'Business',
    'Chemistry',
    'Classical Studies',
    'Communication',
    'Computer Science',
    'Economics',
    'Education',
    'English',
    'Engineering',
    'Environmental Science',
    'French',
    'Gender Studies',
    'Geology',
    'German',
    'Health and Biomedical Sciences Program',
    'Health and Movement Studies',
    'History',
    'International Studies',
    'Kinesiology and Integrative Physiology',
    'Mathematics',
    'Medieval-Renaissance Studies',
    'Music',
    'Philosophy',
    'Physics',
    'Political Science',
    'Pre-Dentistry',
    'Pre-Law',
    'Pre-Med / Pre-Health',
    'Pre-Pharmacy',
    'Pre-Physical Therapy',
    'Pre-Veterinary Sciences',
    'Psychology',
    'Sociology',
    'Spanish',
    'Theatre',
    'Theological Studies',
]
