# http://www.matchcollege.com/top-majors

degrees = [
    'Other',
    'Business and Technology',
    'Business Administration',
    'Liberal Arts',
    'Nursing',
    'Psychology',
    'General Studies',
    'Medical Assistant',
    'Cosmetology',
    'Biology',
    'Accounting',
    'Licensed Practical Nurse (LPN)',
    'Criminal Justice',
    'Nursing Assistant',
    'English',
    'Social Work',
    'Elementary Education',
    'Law',
    'Political Science',
    'Auto Mechanic',
    'Finance',
    'Communications',
    'History',
    'Advertising and Marketing',
    'Sociology',
    'Law and Justice Administration',
    'Economics',
    'Mechanical Engineering',
    'Education',
    'Welding',
    'Early Childhood Education',
    'Educational Leadership and Administration',
    'Electrical Engineering',
    'Dental Assistant',
    'Kinesiology And Exercise Science',
    'Math',
    'Massage Therapy',
    'Bookkeeping',
    'Computer Science',
    'Culinary Arts',
    'Special Education',
    'Chemistry',
    'Healthcare Administration',
    'Civil Engineering',
    'Heating and Air Conditioning (HVAC)',
    'Bus and Truck Driver',
    'Medicine',
    'Information Technology',
    'Pharmacy Technician',
    'Public Administration',
    'Human Services',
    'Paralegal',
    'Computer Networking',
    'Human Resources',
    'Esthetician',
    'Pharmacy',
    'Electrician',
    'Journalism',
    'International Relations',
    'Administrative Assistant',
    'Anthropology',
    'Sports Medicine',
    'Information Systems',
    'Sports Management',
    'Guidance Counselor',
    'Public Health',
    'Graphic Design',
    'Secondary Education',
    'Music',
    'Physical Therapy',
    'Counseling Psychology',
    'Physical Education',
    'Chemical Engineering',
    'Architecture',
    'Diesel Mechanic',
    'Physics',
    'Surgical Technologist',
    'International Business',
    'Nail Technician',
    'Veterinary Assistant',
    'Respiratory Therapy',
    'Behavioral Science',
    'Fire Science',
    'Criminology',
    'Biomedical Engineering',
    'Baking And Pastry',
    'Dental Hygienist',
    'Philosophy',
    'Phlebotomy',
    'Biochemistry',
    'Cinematography And Film',
    'Audiology and Speech Pathology',
    'Physician Assistant',
    'Engineering',
    'Environmental Science',
    'Ministry',
    'Physical Therapist Assistant',
    'Geology',
    'Occupational Therapy',
    'Auto Body',
    'Radiology Technician',
    'Creative Writing',
    'Theology',
    'Geography',
    'Web Design',
    'Computer Aided Design (CAD)',
    'Interior Design',
    'Computer Programming',
    'Animal Science',
    'Clinical Psychology',
    'Substance Abuse and Addiction Counseling',
    'Dentistry',
    'Public Relations',
    'Biomedical Science',
    'Logistics and Supply Chain Management',
    'Audio and Video Production',
    'Mental Health Counseling',
    'Fashion Merchandising',
    'Religious Studies',
    'Aircraft Mechanic',
    'Ultrasound Technician',
    'Neuroscience',
    'Operations Management',
    'Athletic Training',
    'Occupational Therapy Assistant (OTA)',
    'Art History',
    'Public Policy',
    'Animation',
    'Child Development',
    'Fashion Design',
    'Dietetics',
    'Engineering Management',
    'Child Care',
    'Statistics',
    'Systems Engineering',
    'Aviation',
    'Photography',
    'Parks and Recreation Management',
    'Carpentry',
    'Hotel and Hospitality Management',
    'Computer Graphics',
    'Marriage and Family Therapy',
    'Urban Planning',
    'Real Estate',
    'Linguistics',
    'Molecular Biology',
    'Forensic Science',
    'Agriculture',
    'Nutrition',
    'Organizational and Nonprofit Management',
    'School Psychology',
    'Veterinary Medicine',
    'Construction Management',
    'Dance',
    'Exercise Physiology',
    'Legal Studies',
    'Environmental and Wildlife Management',
    'Chiropractic',
    'Property Management',
    'Microbiology',
    'Illustration',
    'Software Engineering',
    'Food Science',
    'Petroleum Engineering',
    'Game Design',
    'Zoology',
    'Horticulture',
    'Industrial Design',
    'Music Management',
    'Radio And Television Broadcasting',
    'Forensic Psychology',
    'Acupuncture',
    'Christian Counseling',
    'Organizational Psychology',
    'Marine Biology',
    'Optometry',
    'Risk Management and Insurance',
    'Makeup Artist',
    'Automotive Engineering',
    'Developmental And Child Psychology',
    'Environmental Health',
    'Air Traffic Controller',
    'Forestry',
    'Jewelry Design',
    'Health Informatics',
    'Equine Studies',
    'Museum Studies',
    'Medical Transcription',
    'Court Reporting',
    'Art Therapy',
    'Podiatry',
    'Sign Language',
    'Gunsmithing',
    'Turf Management',
    'Astronomy',
    'Botany',
    'Music Therapy',
    'Structural Engineering',
    'Wildlife Biology',
    'Archaeology',
    'Holistic Health and Nutrition',
    'Astrophysics',
]
