# https://en.wikipedia.org/wiki/List_of_hobbies

hobbies = [
    '3D printing',
    'Amateur radio',
    'Acting',
    'Baton twirling',
    'Board games',
    'Book restoration',
    'Cabaret',
    'Calligraphy',
    'Candle making',
    'Computer programming',
    'Coffee roasting',
    'Cooking',
    'Coloring',
    'Cosplaying',
    'Couponing',
    'Creative writing',
    'Crocheting',
    'Crossword puzzles',
    'Cryptography',
    'Dance',
    'Digital arts',
    'Drama',
    'Drawing',
    'Do it yourself',
    'Electronics',
    'Embroidery',
    'Fantasy Sports',
    'Fashion',
    'Flower arranging',
    'Foreign language learning',
    'Gaming (tabletop games and role-playing games)',
    'Genealogy',
    'Glassblowing',
    'Gunsmithing',
    'Homebrewing',
    'Ice skating',
    'Jewelry making',
    'Jigsaw puzzles',
    'Juggling',
    'Knapping',
    'Knitting',
    'Kabaddi',
    'Knife making',
    'Kombucha Brewing',
    'Lacemaking',
    'Lapidary',
    'Lego building',
    'Lockpicking',
    'Lucid dreaming',
    'Machining',
    'Macrame',
    'Metalworking',
    'Magic',
    'Model building',
    'Listening to music',
    'Origami',
    'Painting',
    'Playing musical instruments',
    'Pet',
    'Poi',
    'Pottery',
    'Puzzles',
    'Quilting',
    'Reading',
    'Scrapbooking',
    'Sculpting',
    'Sewing',
    'Singing',
    'Sketching',
    'Soapmaking',
    'Stand-up comedy',
    'Tatting',
    'Taxidermy',
    'Video games',
    'Watching movies/television',
    'Web surfing',
    'Whittling',
    'Wikipedia editing',
    'Wood carving',
    'Woodworking',
    'Worldbuilding',
    'Writing',
    'Yoga',
    'Yo-yoing',
    'Air sports',
    'Archery',
    'Astronomy',
    'BASE jumping',
    'Baseball',
    'Basketball',
    'Beekeeping',
    'Bird watching',
    'Blacksmithing',
    'Board sports',
    'Bodybuilding',
    'Brazilian jiu-jitsu',
    'Camping',
    'Dowsing',
    'Driving',
    'Fishing ',
    'Flag football',
    'Flying',
    'Flying disc',
    'Foraging',
    'Freestyle football',
    'Gardening',
    'Ghost hunting',
    'Graffiti',
    'Hooping',
    'Horseback riding',
    'Hunting',
    'Inline skating',
    'Jogging',
    'Kayaking',
    'Kite flying',
    'Kitesurfing',
    'LARPing',
    'Letterboxing',
    'Metal detecting',
    'Motor sports',
    'Mountain biking',
    'Mountaineering',
    'Mushroom hunting/Mycology',
    'Netball',
    'Nordic skating',
    'Orienteering',
    'Paintball',
    'Parkour',
    'Photography',
    'Polo',
    'Rafting',
    'Rappelling',
    'Road biking',
    'Rock climbing',
    'Roller skating',
    'Rugby',
    'Running',
    'Sailing',
    'Sand art',
    'Scouting',
    'Scuba diving',
    'Sculling or Rowing',
    'Topiary',
    'Shooting',
    'Shopping',
    'Skateboarding',
    'Skiing',
    'Skimboarding',
    'Skydiving',
    'Slacklining',
    'Snowboarding',
    'Stone skipping',
    'Surfing',
    'Swimming',
    'Taekwondo',
    'Tai chi',
    'Urban exploration',
    'Vacation',
    'Vehicle restoration',
    'Walking',
    'Water sports',
    'Action figure',
    'Antiquing',
    'Art collecting',
    'Book collecting',
    'Card collecting',
    'Coin collecting',
    'Comic book collecting',
    'Deltiology (postcard collecting)',
    'Die-cast toy',
    'Element collecting',
    'Movie and movie memorabilia collecting',
    'Record collecting',
    'Stamp collecting',
    'Vintage cars',
    'Antiquities',
    'Auto audiophilia',
    'Flower collecting and pressing',
    'Fossil hunting',
    'Insect collecting',
    'Stone collecting',
    'Mineral collecting',
    'Rock balancing',
    'Sea glass collecting',
    'Seashell collecting',
    'Animal fancy',
    'Badminton',
    'Billiards',
    'Bowling',
    'Boxing',
    'Bridge',
    'Cheerleading',
    'Chess',
    'Color guard',
    'Curling',
    'Dancing',
    'Darts',
    'Debate',
    'Fencing',
    'Gymnastics',
    'Laser tag',
    'Marbles',
    'Martial arts',
    'Mahjong',
    'Poker',
    'Slot car racing',
    'Table football',
    'Weightlifting',
    'Airsoft',
    'American football',
    'Archer',
    'Australian rules football',
    'Auto racing',
    'Beach Volleyball',
    'Breakdancing',
    'Climbing',
    'Cricket',
    'Cycling',
    'Disc golf',
    'Dog sport',
    'Equestrianism',
    'Exhibition drill',
    'Field hockey',
    'Figure skating',
    'Fishing',
    'Footbag',
    'Golfing',
    'Handball',
    'Ice hockey',
    'Judo',
    'Jukskei',
    'Kart racing',
    'Knife throwing',
    'Lacrosse',
    'Model aircraft',
    'Pigeon racing',
    'Racquetball',
    'Radio-controlled car racing',
    'Roller derby',
    'Speed skating',
    'Squash',
    'Table tennis',
    'Tennis',
    'Tour skating',
    'Triathlon',
    'Ultimate Disc',
    'Volleyball',
    'Aircraft spotting',
    'Amateur astronomy',
    'Astrology',
    'Bus spotting',
    'Geocaching',
    'Gongoozling',
    'Herping',
    'Meteorology',
    'People watching',
    'Trainspotting',
    'Traveling',
    'Hiking/Backpacking',
    'Whale watching',
    'Satellite watching',
    'Fishkeeping',
    'Learning',
    'Microscopy',
    'Shortwave listening',
    'Videophilia',
    'Clarinet',
    'Cymbals',
    'Drums',
    'Flute',
    'Guitar',
    'Oboe',
    'Organ',
    'Piano',
    'Trombone',
    'Trumpet',
    'Violin',
    'Xylophone',
    'Triangle',
    'Maracas',
    'Kazoo',
    'Tuba',
    'Piccolo',
    'Bass'
]
