# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to=jobs.models.get_resume_path)),
                ('email', models.EmailField(max_length=120)),
                ('cover_letter', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=120, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('min_gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Miniumum GPA')),
                ('years', models.CharField(max_length=120)),
                ('list_date_start', models.DateTimeField(null=True, verbose_name='Listing Start Date')),
                ('list_date_end', models.DateTimeField(null=True, verbose_name='Listing Expiration')),
                ('applicants', models.ManyToManyField(blank=True, related_name='job_applicants', to='jobs.Applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to='accounts.Company')),
                ('degrees', models.ManyToManyField(related_name='job_degrees', to='accounts.Degree')),
                ('universities', models.ManyToManyField(related_name='job_universities', to='accounts.School')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
