# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='universities',
        ),
        migrations.AddField(
            model_name='job',
            name='universities',
            field=models.ManyToManyField(blank=True, to='accounts.School'),
        ),
    ]
