# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degrees',
            field=models.ManyToManyField(related_name='job_degrees', to='accounts.Degree'),
        ),
        migrations.AddField(
            model_name='job',
            name='years',
            field=models.CharField(default='10,11,12,13,14', max_length=120),
            preserve_default=False,
        ),
    ]
