# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='universities',
            field=models.ManyToManyField(related_name='job_universities', to='accounts.School'),
        ),
    ]
