# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
