# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20161027_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='university',
            new_name='grad_uni',
        ),
        migrations.AddField(
            model_name='applicant',
            name='undergrad_uni',
            field=models.CharField(default='Brown University (Business)', max_length=200),
            preserve_default=False,
        ),
    ]
