# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161027_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='grad_uni',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='undergrad_uni',
        ),
    ]
