# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='skills',
            new_name='hobbies',
        ),
    ]
