# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['name'], 'verbose_name': 'degree', 'verbose_name_plural': 'degrees'},
        ),
    ]
