# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 11:03
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.get_resume_path),
        ),
    ]
