# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
