# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161021_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
    ]
