# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
