# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161002_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='GPA'),
        ),
    ]
