# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161021_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='degree_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Associates'), (1, 'Bachelors'), (2, 'Masters'), (3, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='degree_earned',
            field=models.IntegerField(blank=True, choices=[(5, 'Associates'), (6, 'Bachelors'), (7, 'Masters'), (8, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Employer')], null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(choices=[(2, 'Male'), (3, 'Female'), (4, 'Prefer not to answer')], default=4),
        ),
    ]
