# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161023_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='grad_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grad_degree', to='accounts.Degree'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='grad_uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grad_university', to='accounts.School'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='undergrad_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undergrad_degree', to='accounts.Degree'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='undergrad_uni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undergrad_university', to='accounts.School'),
        ),
    ]
