# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161024_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='grad_degree',
        ),
        migrations.AddField(
            model_name='myuser',
            name='grad_degree',
            field=models.ManyToManyField(blank=True, null=True, related_name='grad_degree', to='accounts.Degree'),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='undergrad_degree',
        ),
        migrations.AddField(
            model_name='myuser',
            name='undergrad_degree',
            field=models.ManyToManyField(blank=True, null=True, related_name='undergrad_degree', to='accounts.Degree'),
        ),
    ]
