# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
    ]
